### ISSUE TITLE
Failing MOR test

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#241]
It looks like one of the new MOR tests is failing: http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3380563&build=65141 .  @plindsa , can you please have a look?

**Comment by plindsa** [comment]
It looks like these are just failing because the exodiff tolerances are too tight (thanks @ikalash for pointing that out!).  I just checked in a commit that should fix this by increasing the floor to 1e-9 in the exodiff files.

**Comment by ikalash** [comment]
Thanks for looking at this, @plindsa .  I just tried to run the test again after pulling your fix and unfortunately it is still failing.  It looks like now there are more significant differences, e.g., 

Nodal variables:
   disp_x             rel diff: -1.4527046e-01 ~  1.5382878e-01 = 1.94436e+00 (node 47)
   disp_y             rel diff: -9.1888117e-02 ~  9.2333196e-02 = 1.99518e+00 (node 42)
   disp_z             rel diff:  1.0405098e-01 ~ -1.4198818e-01 = 1.73281e+00 (node 42)

Also, I think the case where values are < machine precision are still getting flagged as failed: 

 --------- Time step 57, -4.8446202e-18 ~ -4.9927944e-18, rel diff:  2.96776e-02 (FAILED)

I'm attaching the log file, which has the detailed output.  We can look at it together on my machine this afternoon if you would like - I can come by when I have time.

[RB.log](https://github.com/gahansen/Albany/files/1612836/RB.log)

**Comment by ikalash** [comment]
I just tried your fix, @plindsa , and everything is passing on my machine.  Thanks for fixing it!

**Comment by plindsa** [comment]
Great!  The RBGen outputs singular values as time steps (so the floor needed adjusted), as well as the corresponding vectors as data (so negatives should be ignored using the eigen_relative keyword).  Finally, the data for small singular values gets more and more uncertain, so I'm only checking the "time-steps" that correspond to singular values that are below the floor threshold I've set.
