### ISSUE TITLE
Partition test failing in dashboard

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#257]
Today the partition test began to fail in the dashboard: 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3431165&build=66228

**Comment by lxmota** [comment]
Ah, missed this. I just committed a fix for it.

**Comment by ikalash** [comment]
Looks like this test is still broken today.  @lxmota can you please have a look?

**Comment by lxmota** [comment]
Ugh, forgot to fix random seed. Fixed.
