### ISSUE TITLE
floating point exceptions in thermo-mechanical tests

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#260]
RPI's thermo-mechanical tests started failing today:

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3437452&build=66342

@lxmota does this have to do with your bulk modulus fix?

**Comment by gahansen** [comment]
It also looks like the thermomechanical can test is failing. I changed the line with "kappa" in J2Model_Def.hpp back to what it was before @lxmota 's commit 26958caacc9362ee6de9c938bb971956c9e634bc and the  ThermoMechanicalCan_thermomech test passes. The FPE is generated down inside the Ifpack2 relaxation solve in MueLu. If I change the preconditioner to Ifpack2, I get the error: 

Ifpack2::ILUT::Compute: zero pivot encountered! Replacing with rownorm and continuing...

@lxmota - any thoughts on what might be broken?

**Comment by lxmota** [comment]
Sorry about this. All those tests will need to be rebased.

The lack of kappa is a serious error in the material models that Max Bloomfield pointed out. The results, even if they pass the tests, are wrong.

**Comment by ibaned** [comment]
@lxmota I agree that more correct physics should always take precedence, and we should do that in this case too. However, these tests are failing to converge and/or getting floating point exceptions, so they will require more than just rebasing to start passing again.

**Comment by gahansen** [comment]
Yes - we expect that we will need to rebaseline the tests, but that will not fix the FPE I don't believe. The addition of kappa in the thermal term appears to create a zero pivot in the preconditioner. Maybe we have the problem setup wrong?

**Comment by lxmota** [comment]
Hmm, that could happen if the material is nearly incompressible, as the bulk modulus would be a very large number, of even infinity if the Poisson's ratio is 0.5.

Are all these RPI tests?

**Comment by gahansen** [comment]
Do we have any other tests that look at thermal expansion other than these?

**Comment by lxmota** [comment]
It appears that we don't other tests for this. Thus the error went undetected for so long.

**Comment by gahansen** [comment]
It looks like the Poisson's ratio is 0.32. Here is the materials file.
[MechanicsWithTemperatureMaterials.yaml.txt](https://github.com/gahansen/Albany/files/1699912/MechanicsWithTemperatureMaterials.yaml.txt)

**Comment by gahansen** [comment]
The tests SCOREC_* are tests that RPI folks committed, but they run on the internal dashboard:

http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany

I created the ThermoMechanicalCan_thermomech test

**Comment by tjfulle** [comment]
I've got a single element thermomechanical test that fails.  Not the same error as the failing RPI tests, but it looks related.  Like @gahansen noted, switching from MueLu as the preconditioner to Ifpack2 gets around the error, but emits warnings.  Using `Prec Type: RILUK` gets around the warnings.  The single element problem should be easier to debug now - hopefully the resolution will fix the RPI tests.

**Comment by tjfulle** [comment]
@lxmota, @gahansen : I have not been able to determine why adding the `kappa` term to the thermomechanical stress update causes FPEs.  But, I believe a more fundamental change to material models to account for thermal expansion can be made.  I've made the following change to the J2 model that allows @gahensen's thermal mechanical can test to run.  In essence, rather than subtract the a thermal contribution from the updated stress at the end of the update, remove the thermal contribution to the deformation gradient at the beginning of the stress update and use only the mechanical portion in the stress update:

```c++
      if (have_temperature_) {
        // Compute the mechanical deformation gradient Fe based on the
        // multiplicative decomposition of the deformation gradient
        //
        //           F = Fe.Ft => Fe = F.inv(Ft)
        //
        // where Ft is the thermal part of F, given as
        //
        //            Ft = Le * I = exp(alpha * dtemp) * I
        minitensor::Tensor<ScalarT> Ft;
        ScalarT dtemp =  temperature_(cell, pt) - ref_temperature_;
        ScalarT thermal_stretch = std::exp(expansion_coeff_ * dtemp);
        Ft = thermal_stretch * I;
        Fe = F * minitensor::inverse(Ft);
      } else {
        Fe = F;
      }
```

`Fe` replaces `F` in the regular stress update.  I think this approach may be more consistent with classical thermo-mechanics (for example, [this paper](http://www.ssm.org.rs/WebTAM/_private/vol28_29/pdf_format/vujolub.pdf)).  It also avoids some issues with very large bulk modulus values for (nearly) incompressible materials.

For pressure-independent plasticity with the assumption of isotropic thermal expansion, the outlined approach and the current approach shouldn't be much different.  I have not investigated why this approach runs to completion for @gahansen's test but not the other.  But, the outlined approach is general to any material model and can support anisotropic thermal expansion easily.

Thoughts?

**Comment by lxmota** [comment]
This is OK with me. My only suggestion, in order to avoid unnecessary computations is to do the following:
        ScalarT const dtemp =  temperature_(cell, pt) - ref_temperature_;
        ScalarT const thermal_stretch = std::exp(expansion_coeff_ * dtemp);
        Fe = F / thermal_stretch;

**Comment by gahansen** [comment]
I like your change, Tim. I am including @maxrpi and @bgranzow for additional input.

**Comment by tjfulle** [comment]
@lxmota will dividing a tensor by a scalar only apply the division to the diagonal?

**Comment by maxrpi** [comment]
@tjfulle , I like your version. It jives nicely with how I conceptualize the various stress contributions.

**Comment by lxmota** [comment]
@tjfulle No, it should apply to all components.

At least that is how I remember I implemented that in minitensor.

**Comment by tjfulle** [comment]
@lxmota, then should I interpret your other comment to mean

```
Fe = F * (1/expansion_coefficient_*I)
```

**Comment by lxmota** [comment]
@tjfulle I mean
  Fe = F / thermal_stretch;
which gives the same result as
   Ft = thermal_stretch * I;
   Fe = F * minitensor::inverse(Ft);

**Comment by tjfulle** [comment]
@lxmota I’m confused how division by a scalar would give the same results as right multiplication by the inverse of a tensor.  In this case we need to scale only the diagonals of F

**Comment by lxmota** [comment]
@tjfulle In this particular case it is the same, as one of the tensors is a multiple of the identity. The scalar can be factored out of the identity:

`A = a * I`

then

`C = A * B = (a * I) * B = a * I * B = a * B`

or 

`C = B * A = B * (I * a) = B * I * a = B * a`

**Comment by tjfulle** [comment]
Well, that’s embarrassing, I swear I passed intro to linear algebra!.  Sometimes you wish you could delete a string of comments...

**Comment by lxmota** [comment]
@tjfulle No worries. It's hard sometimes to remember these details. I'm glad that you discovered a fix for this vexing problem.

**Comment by tjfulle** [comment]
A possible fix for this issue is given in #266.  Just waiting a review before I squash and merge.

**Comment by tjfulle** [comment]
@ibaned, I just merged #266 that *may* resolve the FPEs, though it does not rebaseline any of the affected tests.

**Comment by lxmota** [comment]
Can this issue be closed?

**Comment by gahansen** [comment]
I think there are still a few details left to resolve. The two SCOREC tests are still failing with FPEs, on the line:

NeohookeanModel_Def.hpp : 124
        ScalarT thermal_stretch = std::exp(expansion_coeff_ * dtemp);

The FPE is actually generated in the __libm_exp_e7() function in MKL's libimf.so . I've seen "odd" FPEs of this nature before and have not been able to fully resolve the problem. I'd suggest that I switch from MKL on these tests and see what happens.

**Comment by tjfulle** [comment]
We talked about this issue on Monday.  I believe the consensus was to leave it open until someone at RPI could look at the failing tests more closely

**Comment by ibaned** [comment]
What is the value of `expansion_coeff_ * dtemp` that causes the overflow?

**Comment by gahansen** [comment]
124             ScalarT thermal_stretch = std::exp(expansion_coeff_ * dtemp);
(gdb) p dtemp
$1 = 10.700009922241236
(gdb) p expansion_coeff_
$2 = 100

**Comment by bgranzow** [comment]
It seems pretty possible that the expansion coefficient is in the wrong units / incorrect / just totally meaningless, right?  Usually thermal expansion coefficients are on the order of 10^-6 to 10^-5, right?

**Comment by lxmota** [comment]
Yes, it appears that the value of the thermal expansion coefficient is wrong. It should be quite small and its units are 1/Celsius, 1/Kelvin, or 1/Farenheit, [strain/temperature] so no matter the units, it should be small.

**Comment by tjfulle** [comment]
That does seem to be the case - I would certainly be suspicious of an expansion coefficient on the order of 100 that @gahansen showed

**Comment by gahansen** [comment]
@bgranzow - do you know who might be the best person to check with on that value? I looked over some "git blame" output but the owner isn't clear - maybe you were the original author? I could just change this to 1.e-5 and rebaseline for now given that the original baseline is suspect.

**Comment by bgranzow** [comment]
@gahansen - This is likely my fault. Sorry about that, folks. Not sure what I was thinking when I put that value in. It would be absolutely OK to change it to 1e-5 and rebaseline the test. I can do this if you'd like. I'll need some time to set up a build of Trilinos + Albany on a Sandia machine.

**Comment by gahansen** [comment]
@bgranzow - looks like that did the job. Thank much for fixing those tests. I think we have resolved these FPEs and related issues, I'm going to go ahead and close this issue.
